# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed

# For beginners, we downscale velocity and acceleration limits.
# You can always specify higher scaling factors (<= 1.0) in your motion requests.  # Increase the values below to 1.0 to always move at maximum speed.
default_velocity_scaling_factor: 0.1
default_acceleration_scaling_factor: 0.1

# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]

# As MoveIt! does not support jerk limits, the acceleration limits provided here are the highest values that guarantee
# that no jerk limits will be violated. More precisely, applying Euler differentiation in the worst case (from min accel
# to max accel in 1 ms) the acceleration limits are the ones that satisfy
# max_jerk = (max_acceleration - min_acceleration) / 0.001

joint_limits:
  $(arg arm_id)_finger_joint1:
    has_velocity_limits: true
    max_velocity: 0.1
    has_acceleration_limits: false
    max_acceleration: 0
  $(arg arm_id)_finger_joint2:
    has_velocity_limits: true
    max_velocity: 0.1
    has_acceleration_limits: false
    max_acceleration: 0
  $(arg arm_id)_joint1:
    has_velocity_limits: true
    max_velocity: 2.1750
    has_acceleration_limits: true
    max_acceleration: 3.75
  $(arg arm_id)_joint2:
    has_velocity_limits: true
    max_velocity: 2.1750
    has_acceleration_limits: true
    max_acceleration: 1.875
  $(arg arm_id)_joint3:
    has_velocity_limits: true
    max_velocity: 2.1750
    has_acceleration_limits: true
    max_acceleration: 2.5
  $(arg arm_id)_joint4:
    has_velocity_limits: true
    max_velocity: 2.1750
    has_acceleration_limits: true
    max_acceleration: 3.125
  $(arg arm_id)_joint5:
    has_velocity_limits: true
    max_velocity: 2.6100
    has_acceleration_limits: true
    max_acceleration: 3.75
  $(arg arm_id)_joint6:
    has_velocity_limits: true
    max_velocity: 2.6100
    has_acceleration_limits: true
    max_acceleration: 5
  $(arg arm_id)_joint7:
    has_velocity_limits: true
    max_velocity: 2.6100
    has_acceleration_limits: true
    max_acceleration: 5

